CREATE TABLE IF NOT EXISTS auto_order_requests (
 identifier VARCHAR(255) PRIMARY KEY,
 key_id BIGINT NOT NULL,
 login_id VARCHAR(255) NOT NULL,
 market VARCHAR(100) NOT NULL,
 side VARCHAR(10) NOT NULL,
 status VARCHAR(20) NOT NULL CHECK(status IN ('PENDING','ACCEPTED','REJECTED','UNKNOWN')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_auto_order_requests_unresolved
 ON auto_order_requests(key_id) WHERE status IN ('PENDING','UNKNOWN');
