services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bion_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}
      POSTGRES_DB: ${POSTGRES_DB:-bion}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - C:/data:/var/lib/postgresql/data
    networks:
      - nat

volumes:
  postgres_data:

networks:
  nat:
    driver: bridge
