import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import './pwa.css';

if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('/sw.js'));

async function api(path, options={}) {
  const response = await fetch(`/api${path}`, {credentials:'same-origin', headers:{'Content-Type':'application/json', ...(options.headers||{})}, ...options});
  if (!response.ok) throw new Error((await response.json().catch(()=>({}))).detail || `요청 실패 (${response.status})`);
  return response.status === 204 ? null : response.json();
}

const labels={code:'종목 코드',name:'종목명',minimum_selling_price:'손절가',expected_selling_price:'목표가',origin_minimum_selling_price:'최초 손절가',origin_expected_selling_price:'최초 목표가',temp_price:'현재가',setting_price:'기준가',renewal_cnt:'갱신 단계',pricing_reference_date:'기준 갱신 시각',updated_at:'최근 확인 시각',dividend_rate:'배당수익률',ex_div_date:'배당락일',pay_date:'지급일',uuid:'주문 번호',side:'구분',ord_type:'주문 방식',price:'주문 가격',state:'상태',market:'마켓',created_at:'일시',volume:'주문 수량',executed_volume:'체결 수량',currency:'자산',balance:'보유 수량',locked:'주문 중 수량',avg_buy_price:'평균 매수가',avg_buy_price_modified:'평균가 수정',unit_currency:'기준 통화',id:'번호',source:'구분',operation:'작업',error_type:'오류 종류',message:'내용',user_login_id:'아이디',user_name:'이름',user_role:'권한',user_email:'이메일',deleted:'비활성',email:'이메일 주소',status:'전체 상태',database:'데이터베이스',calculation:'계산 서비스',api_uptime_seconds:'API 가동 시간',error_count:'누적 오류',trading_execution:'자동 실행',scheduler_running:'스케줄러',key_registered:'API 키 등록',auto_on:'자동매매'};
const stateLabels={bid:'매수',ask:'매도',done:'체결 완료',wait:'체결 대기',cancel:'취소',watch:'예약 주문',market:'시장가',limit:'지정가',price:'시장가 매수',UP:'정상',DOWN:'중단',ACTIVE:'사용 중',DISABLED:'사용 안 함'};
const priceKeys=new Set(['minimum_selling_price','expected_selling_price','origin_minimum_selling_price','origin_expected_selling_price','temp_price','setting_price','price','avg_buy_price']);
const dateKeys=new Set(['pricing_reference_date','updated_at','created_at','ex_div_date','pay_date']);
const number=(value,digits=2)=>Number(value).toLocaleString('ko-KR',{maximumFractionDigits:digits});
const signed=value=>`${value>0?'+':''}${number(value)}%`;
function display(key,value){if(value===null||value===undefined||value==='')return '—';if(typeof value==='boolean')return value?'예':'아니오';if(key==='dividend_rate')return `${number(value)}%`;if(key==='api_uptime_seconds'){const hours=Math.floor(value/3600),minutes=Math.floor(value%3600/60);return `${hours}시간 ${minutes}분`}if(priceKeys.has(key))return number(value,8);if(dateKeys.has(key))return String(value).replace('T',' ').slice(0,16);return stateLabels[value]??String(value)}

const tabs=[['upbit','Upbit 추천','코인'],['stock','주식 추천','주식'],['dividends','배당주','배당'],['orders','주문 내역','주문'],['account','내 계좌','계좌'],['profile','내 정보','정보'],['system','시스템','상태'],['errors','오류','오류'],['autos','자동매매','자동'],['settings','계산 설정','설정'],['users','사용자','사용자'],['mail','메일','메일']];

function Login({onLogin}){const [loginId,setLoginId]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[joining,setJoining]=useState(false),[name,setName]=useState('');async function submit(event){event.preventDefault();setError('');try{if(joining){await api('/auth/join',{method:'POST',body:JSON.stringify({login_id:loginId,password,name})});setJoining(false);return}await api('/auth/login',{method:'POST',body:JSON.stringify({login_id:loginId,password})});onLogin()}catch(e){setError(e.message)}}return <main className="login"><form className="card login-card" onSubmit={submit}><img src="/icons/icon-192.png" alt="Trading"/><div><small className="eyebrow">PERSONAL TRADING DESK</small><h1>{joining?'계정 만들기':'다시 오셨군요'}</h1><p>투자 현황과 자동매매를 한곳에서 관리하세요.</p></div>{joining&&<label>이름<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>아이디<input autoFocus value={loginId} onChange={e=>setLoginId(e.target.value)} required/></label><label>비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="primary">{joining?'가입하기':'로그인'}</button><button type="button" className="quiet" onClick={()=>setJoining(!joining)}>{joining?'로그인으로 돌아가기':'새 계정 만들기'}</button></form></main>}
function Empty({text='표시할 데이터가 없습니다.'}){return <div className="empty"><b>아직 데이터가 없습니다</b><span>{text}</span></div>}
function Table({rows,columns}){if(!Array.isArray(rows)||!rows.length)return <Empty/>;const keys=columns||Object.keys(rows[0]);return <div className="table-wrap"><table><thead><tr>{keys.map(key=><th key={key}>{labels[key]||key}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id??row.uuid??row.code??index}>{keys.map(key=><td key={key}>{display(key,row[key])}</td>)}</tr>)}</tbody></table></div>}

function RecommendationCards({rows,market}){if(!rows?.length)return <Empty text="다음 수집 주기에 조건에 맞는 종목이 자동으로 추가됩니다."/>;return <div className="recommendations">{rows.map(row=>{const range=Number(row.expected_selling_price)-Number(row.minimum_selling_price);const progress=range?100-(Number(row.expected_selling_price)-Number(row.temp_price))*100/range:0;const change=Number(row.setting_price)?(Number(row.temp_price)-Number(row.setting_price))*100/Number(row.setting_price):0;const visual=Math.max(0,Math.min(100,progress));return <article className="recommendation" key={row.code}><div className="recommendation-head"><div><span className={`market ${market}`}>{market==='upbit'?'UPBIT':'STOCK'}</span><h3>{row.name}</h3><small>{row.code}</small></div><div className={`change ${change>=0?'up':'down'}`}><small>기준가 대비</small><strong>{signed(change)}</strong></div></div><div className="price-main"><small>현재가</small><strong>{number(row.temp_price,8)}</strong></div><div className="progress-label"><span>손절가 {number(row.minimum_selling_price,8)}</span><b>목표 도달 {number(progress,0)}%</b><span>목표가 {number(row.expected_selling_price,8)}</span></div><div className="progress"><i style={{width:`${visual}%`}}/></div><div className="meta"><span><small>기준가</small>{number(row.setting_price,8)}</span><span><small>갱신 단계</small>{row.renewal_cnt}단계</span><span><small>최근 갱신</small>{display('pricing_reference_date',row.pricing_reference_date)}</span></div></article>})}</div>}
function DividendCards({rows}){if(!rows?.length)return <Empty text="배당 정보 수집이 끝나면 이곳에 표시됩니다."/>;return <><p className="summary">배당수익률 상위 <b>{rows.length}</b>개 종목</p><div className="dividend-grid">{rows.map(row=><article className="card dividend" key={row.code}><div><h3>{row.name}</h3><small>{row.code}</small></div><strong>{number(row.dividend_rate)}%</strong></article>)}</div></>}

function Account({rows,reload,setError}){const [access,setAccess]=useState(''),[secret,setSecret]=useState(''),[saving,setSaving]=useState(false);async function save(){setSaving(true);setError('');try{await api('/upbit/key',{method:'PUT',body:JSON.stringify({access_key:access,secret_key:secret})});setAccess('');setSecret('');await reload()}catch(e){setError(e.message)}finally{setSaving(false)}}return <div className="stack"><section className="card form narrow"><h3>Upbit API 키</h3><p className="hint">키는 서버에만 저장되며 화면에 다시 표시되지 않습니다.</p><label>Access Key<input value={access} onChange={e=>setAccess(e.target.value)} autoComplete="off"/></label><label>Secret Key<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} autoComplete="new-password"/></label><button className="primary" disabled={saving||!access||!secret} onClick={save}>{saving?'저장 중…':'API 키 저장'}</button></section><section><h2 className="section-title">보유 자산</h2><Table rows={rows}/></section></div>}
function Profile({user,onSaved,setError}){const [name,setName]=useState(user.user_name||''),[email,setEmail]=useState(user.user_email||''),[password,setPassword]=useState('');async function save(){setError('');try{await api('/profile',{method:'PUT',body:JSON.stringify({name,email:email||null,phone:null,password:password||null})});setPassword('');await onSaved()}catch(e){setError(e.message)}}return <div className="card form narrow"><h3>프로필</h3><label>이름<input value={name} onChange={e=>setName(e.target.value)}/></label><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>새 비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="변경할 때만 입력"/></label><button className="primary" onClick={save}>변경사항 저장</button></div>}
function Settings({rows,onChange,onSave}){if(!rows?.length)return <Empty/>;const fields=[['expected_high_percentage','목표 상승률','기준 가격에서 목표 매도가까지의 비율','%'],['expected_low_percentage','허용 하락률','기준 가격에서 손절가까지의 비율','%'],['highest_price_reference_days','분석 기간','고점과 거래량 계산에 사용할 기간','일']];return <div className="settings-grid">{rows.map((row,index)=><article className="card form" key={row.name}><div className="setting-title"><span className={`market ${row.name}`}>{row.name==='upbit'?'UPBIT':'STOCK'}</span><h3>{row.name==='upbit'?'Upbit 계산 기준':'주식 계산 기준'}</h3></div>{fields.map(([key,label,help,unit])=><label key={key}>{label}<small>{help}</small><div className="input-unit"><input type="number" value={row[key]} onChange={e=>onChange(index,key,e.target.value)}/><span>{unit}</span></div></label>)}<label className="check"><input type="checkbox" checked={row.volume_check} onChange={e=>onChange(index,'volume_check',e.target.checked)}/><span><b>거래량 조건 사용</b><small>추천 계산에 거래량 증가 여부를 반영합니다.</small></span></label><button className="primary" onClick={()=>onSave(row)}>설정 저장</button></article>)}</div>}

function App(){
 const [user,setUser]=useState(null),[ready,setReady]=useState(false),[tab,setTab]=useState('system'),[data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[installPrompt,setInstallPrompt]=useState(null);
 const loadUser=()=>api('/auth/me').then(setUser).catch(()=>setUser(null)).finally(()=>setReady(true));
 useEffect(()=>{loadUser();const handler=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',handler);return()=>window.removeEventListener('beforeinstallprompt',handler)},[]);
 const load=()=>{setData(null);setError('');setNotice('');let path=['stock','upbit'].includes(tab)?`/recommendations/${tab}`:`/admin/${tab}`;if(['dividends','orders'].includes(tab))path=`/${tab}`;if(tab==='account')path='/upbit/accounts';if(tab==='profile')path='/auth/me';if(tab==='mail')path='/admin/mail-targets';return api(path).then(setData).catch(e=>setError(e.message))};
 const selectTab=key=>{setData(null);setError('');setNotice('');setTab(key)};
 useEffect(()=>{if(user)load()},[user,tab]);
 async function toggleAuto(row){setError('');try{await api(`/admin/autos/${encodeURIComponent(row.user_login_id)}`,{method:'PUT',body:JSON.stringify({auto_on:!row.auto_on})});setData(await api('/admin/autos'))}catch(e){setError(e.message)}}
 async function saveSetting(row){setError('');try{await api(`/admin/settings/${row.name}`,{method:'PUT',body:JSON.stringify({expected_high_percentage:+row.expected_high_percentage,expected_low_percentage:+row.expected_low_percentage,highest_price_reference_days:+row.highest_price_reference_days,volume_check:!!row.volume_check})});setNotice('설정을 저장했습니다. 다음 계산부터 적용됩니다.')}catch(e){setError(e.message)}}
 if(!ready)return <main className="center"><div className="loader"/></main>;if(!user)return <Login onLogin={loadUser}/>;
 const isAdmin=['ADMIN','MASTER'].includes(user.user_role),visible=tabs.filter(([key])=>isAdmin||['stock','upbit','dividends','orders','account','profile'].includes(key)),current=tabs.find(item=>item[0]===tab);
 return <div className="layout"><aside><div className="brand"><img src="/icons/icon-192.png" alt=""/><div><h2>Trading</h2><p>{user.user_name} · {user.user_role}</p></div></div>{installPrompt&&<button className="install" onClick={async()=>{await installPrompt.prompt();setInstallPrompt(null)}}>앱으로 설치</button>}<nav>{visible.map(([key,label,short])=><button className={tab===key?'active':''} onClick={()=>selectTab(key)} key={key}><span>{label}</span><small>{short}</small></button>)}</nav><button className="logout quiet" onClick={async()=>{await api('/auth/logout',{method:'POST'});setUser(null)}}>로그아웃</button></aside><main><header><div><small className="eyebrow">PERSONAL TRADING DESK</small><h1>{current?.[1]}</h1></div><div className="header-actions"><span className="badge"><i/> 정상 운영</span><button className="refresh quiet" onClick={load} disabled={!data}>새로고침</button></div></header>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}{!data&&!error&&<div className="loading-row"><div className="loader"/>데이터를 불러오는 중입니다.</div>}{data&&tab==='system'&&<section className="status-grid">{Object.entries(data).map(([key,value])=><article className="card status-card" key={key}><small>{labels[key]||key}</small><strong>{display(key,value)}</strong></article>)}</section>}{data&&['stock','upbit'].includes(tab)&&<RecommendationCards rows={data} market={tab}/>} {data&&tab==='dividends'&&<DividendCards rows={data}/>} {data&&tab==='orders'&&<Table rows={data}/>} {data&&tab==='account'&&<Account rows={data} reload={load} setError={setError}/>} {data&&tab==='profile'&&<Profile user={data} onSaved={loadUser} setError={setError}/>} {data&&tab==='errors'&&<><p className="summary">누적 오류 <b>{data.total}</b>건 · 최근 50건</p><Table rows={data.items} columns={['created_at','source','operation','error_type','message']}/></>} {Array.isArray(data)&&tab==='autos'&&<div className="auto-grid">{data.map(row=><article className="card auto-card" key={row.user_login_id}><div><h3>{row.user_name}</h3><small>{row.user_login_id}</small></div><span className={`status-pill ${row.auto_on?'on':'off'}`}>{row.auto_on?'자동매매 사용 중':'자동매매 중지'}</span><p>{row.key_registered?'Upbit API 키가 등록되어 있습니다.':'API 키 등록 후 사용할 수 있습니다.'}</p><button className={row.auto_on?'danger':'primary'} disabled={!row.key_registered} onClick={()=>toggleAuto(row)}>{row.auto_on?'자동매매 끄기':'자동매매 켜기'}</button></article>)}</div>} {Array.isArray(data)&&tab==='settings'&&<Settings rows={data} onChange={(index,key,value)=>setData(data.map((row,i)=>i===index?{...row,[key]:value}:row))} onSave={saveSetting}/>} {data&&tab==='users'&&<Table rows={data}/>} {data&&tab==='mail'&&<><Table rows={data}/><button className="primary add-button" onClick={async()=>{const email=prompt('추가할 이메일 주소');if(email){try{await api('/admin/mail-targets',{method:'POST',body:JSON.stringify({email})});load()}catch(e){setError(e.message)}}}}>메일 수신자 추가</button></>}</main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
