import React, {useCallback, useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api, createRequestGate, orderStatus} from './api';
import './style.css';
import './pwa.css';
import './pagination.css';
import './review.css';

if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('/sw.js'));

const labels={code:'종목 코드',name:'종목명',minimum_selling_price:'손절가',expected_selling_price:'목표가',origin_minimum_selling_price:'최초 손절가',origin_expected_selling_price:'최초 목표가',temp_price:'현재가',setting_price:'기준가',renewal_cnt:'갱신 단계',pricing_reference_date:'기준 갱신 시각',updated_at:'최근 확인 시각',dividend_rate:'배당수익률',ex_div_date:'배당락일',pay_date:'지급일',uuid:'주문 번호',side:'구분',ord_type:'주문 방식',price:'주문 가격',state:'상태',market:'마켓',created_at:'일시',volume:'주문 수량',executed_volume:'체결 수량',currency:'자산',balance:'주문 가능',quantity:'총 보유량',locked:'주문 중',avg_buy_price:'평균 매수가',current_price:'현재가',valuation:'평가금액',purchase_amount:'매수금액',profit_rate:'수익률',avg_buy_price_modified:'평균가 수정',unit_currency:'기준 통화',id:'번호',source:'구분',operation:'작업',error_type:'오류 종류',message:'내용',user_login_id:'아이디',user_name:'이름',user_role:'권한',user_email:'이메일',deleted:'비활성',email:'이메일 주소',status:'전체 상태',database:'데이터베이스',calculation:'계산 서비스',api_uptime_seconds:'API 가동 시간',error_count:'누적 오류',trading_execution:'자동 실행',scheduler_running:'스케줄러',key_registered:'API 키 등록',auto_on:'자동매매'};
const stateLabels={bid:'매수',ask:'매도',done:'체결 완료',wait:'체결 대기',cancel:'취소',watch:'예약 주문',market:'시장가',limit:'지정가',price:'시장가 매수',UP:'정상',DOWN:'중단',ACTIVE:'사용 중',DISABLED:'사용 안 함',FETCH_PRICE:'종목 가격 조회',AUTO_ORDER:'자동매매',SCHEDULE_UPDATE:'추천 가격 갱신',SAVE_HISTORY_ITEM:'가격 이력 저장',SYNC_ORDER_HISTORY:'주문 내역 동기화',RECOMMENDATION_BALANCE:'보유 종목 확인',ConnectError:'네트워크 연결 실패',HTTPStatusError:'외부 API 응답 오류'};
const priceKeys=new Set(['minimum_selling_price','expected_selling_price','origin_minimum_selling_price','origin_expected_selling_price','temp_price','setting_price','price','avg_buy_price','current_price','valuation','purchase_amount']);
const dateKeys=new Set(['pricing_reference_date','updated_at','created_at','ex_div_date','pay_date']);
const number=(value,digits=2)=>Number(value).toLocaleString('ko-KR',{maximumFractionDigits:digits});
const signed=value=>`${value>0?'+':''}${number(value)}%`;
function display(key,value){if(value===null||value===undefined||value==='')return '—';if(typeof value==='boolean')return value?'예':'아니오';if(['dividend_rate','profit_rate'].includes(key))return `${number(value)}%`;if(key==='api_uptime_seconds'){const hours=Math.floor(value/3600),minutes=Math.floor(value%3600/60);return `${hours}시간 ${minutes}분`}if(priceKeys.has(key))return number(value,8);if(dateKeys.has(key))return String(value).replace('T',' ').slice(0,16);return stateLabels[value]??String(value)}

const tabs=[['upbit','Upbit 추천','코인'],['stock','주식 추천','주식'],['dividends','배당주','배당'],['orders','주문 내역','주문'],['account','내 계좌','계좌'],['profile','내 정보','정보'],['system','시스템','상태'],['errors','오류','오류'],['autos','자동매매','자동'],['settings','계산 설정','설정'],['users','사용자','사용자'],['mail','메일','메일']];

function Login({onLogin,message}){const [loginId,setLoginId]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[joining,setJoining]=useState(false),[name,setName]=useState('');async function submit(event){event.preventDefault();setError('');try{if(joining){await api('/auth/join',{method:'POST',body:JSON.stringify({login_id:loginId,password,name})});setJoining(false);setPassword('');return}await api('/auth/login',{method:'POST',body:JSON.stringify({login_id:loginId,password})});onLogin()}catch(e){setError(e.message)}}return <main className="login"><section className="login-shell"><div className="login-intro"><img src="/icons/icon-192.png" alt="Trading"/><small className="eyebrow">PERSONAL TRADING DESK</small><h1>내 투자 흐름을<br/>한눈에 확인하세요.</h1><p>추천 종목, 보유 자산과 자동매매 상태를 안전하게 관리합니다.</p></div><form className="login-form" onSubmit={submit}><div><h2>{joining?'새 계정 만들기':'로그인'}</h2><p>{joining?'필요한 정보만 입력해 시작하세요.':'계속하려면 계정 정보를 입력하세요.'}</p></div>{joining&&<label>이름<input value={name} onChange={e=>setName(e.target.value)} required autoComplete="name"/></label>}<label>아이디<input autoFocus value={loginId} onChange={e=>setLoginId(e.target.value)} required autoComplete="username"/></label><label>비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete={joining?'new-password':'current-password'}/></label>{(error||message)&&<div className="error" role="alert">{error||message}</div>}<button className="primary">{joining?'계정 만들기':'로그인'}</button><button type="button" className="text-button" onClick={()=>{setJoining(!joining);setError('')}}>{joining?'이미 계정이 있나요? 로그인':'처음이신가요? 계정 만들기'}</button></form></section></main>}
function Empty({text='표시할 데이터가 없습니다.'}){return <div className="empty"><b>아직 데이터가 없습니다</b><span>{text}</span></div>}
function usePagination(rows,size){const [page,setPage]=useState(0),pages=Math.max(1,Math.ceil((rows?.length||0)/size));useEffect(()=>setPage(value=>Math.min(value,pages-1)),[pages]);return {page,setPage,pages,items:(rows||[]).slice(page*size,(page+1)*size)}}
function Pager({page,pages,onChange}){if(pages<=1)return null;return <nav className="pager" aria-label="페이지 이동"><button className="quiet" disabled={page===0} onClick={()=>onChange(page-1)}>이전</button><span><b>{page+1}</b> / {pages}</span><button className="quiet" disabled={page+1===pages} onClick={()=>onChange(page+1)}>다음</button></nav>}
function Table({rows,columns}){if(!Array.isArray(rows)||!rows.length)return <Empty/>;const keys=columns||Object.keys(rows[0]);return <div className="table-wrap"><table><thead><tr>{keys.map(key=><th key={key}>{labels[key]||key}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id??row.uuid??row.code??index}>{keys.map(key=><td data-label={labels[key]||key} key={key}>{display(key,row[key])}</td>)}</tr>)}</tbody></table></div>}

function RecommendationCards({rows,market}){const pagination=usePagination(rows,9);if(!rows?.length)return <Empty text="다음 수집 주기에 조건에 맞는 종목이 자동으로 추가됩니다."/>;return <><p className="summary">갱신 단계 우선 · 같은 단계는 목표 도달률 순 · 전체 <b>{rows.length}</b>개</p><div className="recommendations">{pagination.items.map(row=>{const range=Number(row.expected_selling_price)-Number(row.minimum_selling_price);const progress=range?100-(Number(row.expected_selling_price)-Number(row.temp_price))*100/range:0;const change=Number(row.setting_price)?(Number(row.temp_price)-Number(row.setting_price))*100/Number(row.setting_price):0;const visual=Math.max(0,Math.min(100,progress));return <article className={`recommendation ${row.owned?'owned':''}`} key={row.code}><div className="recommendation-head"><div><div className="tag-row"><span className={`market ${market}`}>{market==='upbit'?'UPBIT':'STOCK'}</span>{row.owned&&<span className="owned-badge">보유 중 · {number(row.owned_quantity,8)}</span>}</div><h3>{row.name}</h3><small>{row.code}</small></div><div className={`change ${change>=0?'up':'down'}`}><small>기준가 대비</small><strong>{signed(change)}</strong></div></div><div className="price-main"><small>현재가</small><strong>{number(row.temp_price,8)}</strong></div><div className="progress-label"><span>손절가 {number(row.minimum_selling_price,8)}</span><b>목표 도달 {number(progress,0)}%</b><span>목표가 {number(row.expected_selling_price,8)}</span></div><div className="progress"><i style={{width:`${visual}%`}}/></div><div className="meta"><span><small>기준가</small>{number(row.setting_price,8)}</span><span><small>갱신 단계</small>{row.renewal_cnt}단계</span><span><small>최근 갱신</small>{display('pricing_reference_date',row.pricing_reference_date)}</span></div></article>})}</div><Pager page={pagination.page} pages={pagination.pages} onChange={pagination.setPage}/></>}
function DividendCards({rows}){const pagination=usePagination(rows,12);if(!rows?.length)return <Empty text="배당 정보 수집이 끝나면 이곳에 표시됩니다."/>;return <><div className="info-note"><b>배당수익률이란?</b><span>최근 공시 기준 주당 배당금을 현재 주가로 나눈 연 환산 비율입니다. 실제 지급액과 향후 배당을 보장하는 수치는 아닙니다.</span></div><p className="summary">배당수익률 상위 <b>{rows.length}</b>개 종목 · 네이버 금융 기준</p><div className="dividend-grid">{pagination.items.map(row=><article className="card dividend" key={row.code}><div><h3>{row.name}</h3><small>{row.code}</small></div><strong>{number(row.dividend_rate)}%</strong></article>)}</div><Pager page={pagination.page} pages={pagination.pages} onChange={pagination.setPage}/></>}

function Account({snapshot,reload,setError}) {
 const [access,setAccess]=useState(''),[secret,setSecret]=useState(''),[saving,setSaving]=useState(false),[showKeys,setShowKeys]=useState(false);
 const saveLock=useRef(false),assets=snapshot?.assets||[],incomplete=snapshot?.valuation_complete===false;
 const money=(value,digits=0)=>value==null?'시세 확인 불가':`₩ ${number(value,digits)}`;
 async function save(){if(saveLock.current)return;saveLock.current=true;setSaving(true);setError('');try{await api('/upbit/key',{method:'PUT',body:JSON.stringify({access_key:access.trim(),secret_key:secret.trim()})});setAccess('');setSecret('');setShowKeys(false);await reload()}catch(e){setError(e)}finally{saveLock.current=false;setSaving(false)}}
 return <div className="stack"><section className="account-summary"><small>{incomplete?'확인된 평가금액':'총 평가금액'}</small><strong>{money(snapshot?.total_valuation)}</strong><span>보유 수량과 주문 중 수량을 현재가로 환산한 금액입니다.</span>{incomplete&&<span role="status">{(snapshot.unpriced_currencies||[]).join(', ')||'일부 자산'}의 원화 시세를 확인할 수 없어 합계에서 제외했습니다.</span>}</section><section><div className="section-head"><h2 className="section-title">보유 자산</h2><button className="quiet compact" onClick={()=>setShowKeys(!showKeys)}>{showKeys?'닫기':'API 키 관리'}</button></div>{!assets.length?<Empty text="Upbit API 키 등록 상태와 실제 보유 자산을 확인해 주세요."/>:<div className="asset-grid">{assets.map(row=><article className="card asset" key={row.currency}><div className="asset-head"><div><h3>{row.currency}</h3><small>총 {number(row.quantity,8)}</small></div><strong>{money(row.valuation)}</strong></div>{row.currency!=='KRW'&&<><div className="asset-prices"><span><small>현재가</small>{money(row.current_price,8)}</span><span><small>평균 매수가</small>{row.avg_buy_price==null?'—':`${number(row.avg_buy_price,8)} ${row.unit_currency||'KRW'}`}</span></div><div className={`asset-return ${row.profit_rate==null?'':Number(row.profit_rate)>=0?'up':'down'}`}>평가 수익률 <b>{display('profit_rate',row.profit_rate)}</b></div></>}</article>)}</div>}</section>{showKeys&&<section className="card form narrow key-form"><h3>Upbit API 키 변경</h3><p className="hint">키는 서버에만 저장되며 화면에 다시 표시되지 않습니다.</p><label>Access Key<input value={access} onChange={e=>setAccess(e.target.value)} autoComplete="off"/></label><label>Secret Key<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} autoComplete="new-password"/></label><button className="primary" disabled={saving||!access.trim()||!secret.trim()} onClick={save}>{saving?'저장 중…':'API 키 저장'}</button></section>}</div>
}
function Orders({rows}) {
 const pagination=usePagination(rows,10);
 if(!rows?.length)return <Empty text="자동매매 주문이 생성되면 이곳에 표시됩니다."/>;
 return <><p className="summary">최근 주문 <b>{rows.length}</b>건</p><div className="order-list">{pagination.items.map(row=>{const marketBuy=row.side==='bid'&&row.ord_type==='price',cancel=orderStatus(row);return <article className="card order" key={row.uuid}><div className="order-head"><div><span className={`order-side ${row.side}`}>{display('side',row.side)}</span><h3>{row.market}</h3></div><span className={`order-state ${row.state}`}>{cancel?.label||display('state',row.state)}</span></div><div className="order-values"><span><small>주문 방식</small>{display('ord_type',row.ord_type)}</span>{row.price&&<span><small>{marketBuy?'요청한 주문 금액':'주문 가격'}</small>{display('price',row.price)}</span>}{!marketBuy&&row.volume&&<span><small>주문 수량</small>{display('volume',row.volume)}</span>}<span className="executed"><small>실제 체결 수량</small>{display('executed_volume',row.executed_volume)}</span></div>{cancel&&<p className="order-note">{cancel.note}</p>}<div className="order-foot"><time>{display('created_at',row.created_at)}</time><details><summary>주문 번호 보기</summary><code>{row.uuid}</code></details></div></article>})}</div><Pager page={pagination.page} pages={pagination.pages} onChange={pagination.setPage}/></>
}
function ErrorLog({initial,setError}) {
 const [result,setResult]=useState(initial),[loading,setLoading]=useState(false),[source,setSource]=useState(''),[keyword,setKeyword]=useState('');
 const applied=useRef({source:'',keyword:''}),requests=useRef(createRequestGate()),pages=Math.max(1,Math.ceil(result.total/50));
 useEffect(()=>()=>requests.current.cancel(),[]);
 async function move(page,filters=applied.current){const request=requests.current.begin();setLoading(true);setError('');try{const query=new URLSearchParams({page:String(page),...filters});const next=await api(`/admin/errors?${query}`,{signal:request.signal});if(request.isCurrent()){applied.current=filters;setResult(next)}}catch(e){if(request.isCurrent())setError(e)}finally{if(request.isCurrent())setLoading(false)}}
 return <><form className="error-filters" onSubmit={e=>{e.preventDefault();move(0,{source,keyword:keyword.trim()})}}><label>오류 구분<select value={source} onChange={e=>setSource(e.target.value)}><option value="">전체</option><option value="UPBIT">Upbit</option><option value="STOCK">주식</option><option value="SYSTEM">시스템</option></select></label><label>작업·종류·내용 검색<input value={keyword} maxLength={100} onChange={e=>setKeyword(e.target.value)} placeholder="예: 429, FETCH_PRICE"/></label><button className="primary" type="submit">검색</button></form><p className="summary">조회된 오류 <b>{result.total}</b>건 · 페이지당 50건</p>{loading?<div className="loading-row" role="status"><div className="loader"/>불러오는 중입니다.</div>:<Table rows={result.items} columns={['created_at','source','operation','error_type','message']}/>}<Pager page={result.page} pages={pages} onChange={move}/></>
}
function Profile({user,onSaved,setError}){const [name,setName]=useState(user.user_name||''),[email,setEmail]=useState(user.user_email||''),[password,setPassword]=useState('');async function save(){setError('');try{await api('/profile',{method:'PUT',body:JSON.stringify({name,email:email||null,password:password||null})});setPassword('');await onSaved()}catch(e){setError(e)}}return <div className="card form narrow"><h3>프로필</h3><label>이름<input value={name} onChange={e=>setName(e.target.value)}/></label><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>새 비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="변경할 때만 입력"/></label><button className="primary" onClick={save}>변경사항 저장</button></div>}
function Settings({rows,onChange,onSave,pending}) {
 if(!rows?.length)return <Empty/>;
 const fields=[['expected_high_percentage','목표 상승률','기준 가격에서 목표 매도가까지의 비율','%',1,1000],['expected_low_percentage','허용 하락률','목표 상승률보다 작아야 합니다.','%',-99,999],['highest_price_reference_days','분석 기간','조회 가능한 범위: 3~200일','일',3,200]];
 return <div className="settings-grid">{rows.map((row,index)=><form className="card form" key={row.name} onSubmit={e=>{e.preventDefault();onSave(row)}}><div className="setting-title"><span className={`market ${row.name}`}>{row.name==='upbit'?'UPBIT':'STOCK'}</span><h3>{row.name==='upbit'?'Upbit 계산 기준':'주식 계산 기준'}</h3></div>{fields.map(([key,label,help,unit,min,max])=><label key={key}>{label}<small>{help}</small><div className="input-unit"><input type="number" value={row[key]} required step="1" min={min} max={key==='expected_low_percentage'?Math.min(max,Number(row.expected_high_percentage)-1):max} onChange={e=>onChange(index,key,e.target.value)}/><span>{unit}</span></div></label>)}<label className="check"><input type="checkbox" checked={row.volume_check} onChange={e=>onChange(index,'volume_check',e.target.checked)}/><span><b>거래량 조건 사용</b><small>추천 계산에 거래량 증가 여부를 반영합니다.</small></span></label><button className="primary" disabled={pending.includes(`settings-${row.name}`)}>{pending.includes(`settings-${row.name}`)?'저장 중…':'설정 저장'}</button></form>)}</div>
}

function App() {
 const [user,setUser]=useState(null),[ready,setReady]=useState(false),[tab,setTab]=useState('upbit'),[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[authMessage,setAuthMessage]=useState(''),[installPrompt,setInstallPrompt]=useState(null),[pending,setPending]=useState([]);
 const requests=useRef(createRequestGate()),authRequests=useRef(createRequestGate()),activeTab=useRef('upbit'),view=useRef(0),actions=useRef(new Set());
 const expireSession=useCallback(()=>{requests.current.cancel();view.current++;setData(null);setUser(null);setAuthMessage('로그인이 만료되었습니다. 다시 로그인해 주세요.')},[]);
 const handleError=useCallback(e=>{if(e?.status===401){expireSession();return}setError(typeof e==='string'?e:e?.message||'요청을 처리하지 못했습니다.')},[expireSession]);
 const loadUser=useCallback(async()=>{const request=authRequests.current.begin();try{const next=await api('/auth/me',{signal:request.signal});if(!request.isCurrent())return;if(!['ADMIN','MASTER'].includes(next.user_role)&&!['stock','upbit','dividends','orders','account','profile'].includes(activeTab.current)){activeTab.current='upbit';setTab('upbit')}setUser(next);setAuthMessage('')}catch(e){if(request.isCurrent()){setUser(null);if(e.status!==401)setAuthMessage(e.message)}}finally{if(request.isCurrent())setReady(true)}},[]);
 useEffect(()=>{loadUser();const handler=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',handler);return()=>{authRequests.current.cancel();window.removeEventListener('beforeinstallprompt',handler)}},[loadUser]);
 const load=useCallback(async()=>{
  if(activeTab.current!==tab)return;
  const request=requests.current.begin();view.current++;setLoading(true);setData(null);setError('');setNotice('');
  let path=['stock','upbit'].includes(tab)?`/recommendations/${tab}`:`/admin/${tab}`;
  if(['dividends','orders'].includes(tab))path=`/${tab}`;
  if(tab==='account')path='/upbit/accounts';if(tab==='profile')path='/auth/me';if(tab==='mail')path='/admin/mail-targets';
  try{const next=await api(path,{signal:request.signal});if(request.isCurrent())setData(next)}catch(e){if(request.isCurrent())handleError(e)}finally{if(request.isCurrent())setLoading(false)}
 },[tab,handleError]);
 useEffect(()=>{if(user)load();return()=>requests.current.cancel()},[user,load]);
 function selectTab(key){if(key===activeTab.current)return;requests.current.cancel();view.current++;activeTab.current=key;setData(null);setLoading(true);setError('');setNotice('');setTab(key)}
 async function mutate(key,action,{refresh=false,message=''}={}) {
  if(actions.current.has(key))return;
  const currentView=view.current;actions.current.add(key);setPending([...actions.current]);setError('');setNotice('');
  try{await action();if(view.current===currentView){if(refresh)await load();else if(message)setNotice(message)}}catch(e){if(view.current===currentView)handleError(e)}finally{actions.current.delete(key);setPending([...actions.current])}
 }
 async function logout(){await mutate('logout',async()=>{await api('/auth/logout',{method:'POST'});requests.current.cancel();authRequests.current.cancel();view.current++;setUser(null);setData(null);setAuthMessage('')})}
 function saveSetting(row){return mutate(`settings-${row.name}`,()=>api(`/admin/settings/${row.name}`,{method:'PUT',body:JSON.stringify({expected_high_percentage:Number(row.expected_high_percentage),expected_low_percentage:Number(row.expected_low_percentage),highest_price_reference_days:Number(row.highest_price_reference_days),volume_check:!!row.volume_check})}),{message:'설정을 저장했습니다. 다음 계산부터 적용됩니다.'})}
 if(!ready)return <main className="center"><div className="loader"/></main>;
 if(!user)return <Login onLogin={loadUser} message={authMessage}/>;
 const isAdmin=['ADMIN','MASTER'].includes(user.user_role),visible=tabs.filter(([key])=>isAdmin||['stock','upbit','dividends','orders','account','profile'].includes(key)),current=tabs.find(item=>item[0]===tab),currentView=view.current;
 const scopedError=e=>{if(view.current===currentView)handleError(e)};
 const statusLabel=loading?'조회 중':error?'조회 실패':data?'조회 완료':'대기 중';
 return <div className="layout"><aside><div className="brand"><img src="/icons/icon-192.png" alt=""/><div><h2>Trading</h2><p>{user.user_name} · {user.user_role}</p></div></div>{installPrompt&&<button className="install" onClick={async()=>{try{await installPrompt.prompt();setInstallPrompt(null)}catch(e){handleError(e)}}}>앱으로 설치</button>}<nav>{visible.map(([key,label,short])=><button className={tab===key?'active':''} onClick={()=>selectTab(key)} key={key}><span>{label}</span><small>{short}</small></button>)}</nav><button className="logout quiet" disabled={pending.includes('logout')} onClick={logout}>로그아웃</button></aside><main><header><div><small className="eyebrow">PERSONAL TRADING DESK</small><h1>{current?.[1]}</h1></div><div className="header-actions"><span className={`badge ${error?'failed':''}`} role="status">{statusLabel}</span><button className="refresh quiet" onClick={load} disabled={loading}>{error?'다시 시도':'새로고침'}</button></div></header>
 {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}{loading&&<div className="loading-row" role="status"><div className="loader"/>데이터를 불러오는 중입니다.</div>}
 {data&&tab==='system'&&<section className="status-grid">{Object.entries(data).map(([key,value])=><article className="card status-card" key={key}><small>{labels[key]||key}</small><strong>{display(key,value)}</strong></article>)}</section>}
 {data&&['stock','upbit'].includes(tab)&&<>{tab==='upbit'&&data.some(row=>row.owned===null)&&<div className="info-note" role="status">보유 자산을 확인하지 못했습니다. 보유 표시 없이 추천 순서대로 표시합니다.</div>}<RecommendationCards key={tab} rows={data} market={tab}/></>}
 {data&&tab==='dividends'&&<DividendCards rows={data}/>}
 {data&&tab==='orders'&&<Orders rows={data}/>}
 {data&&tab==='account'&&<Account snapshot={data} reload={load} setError={scopedError}/>}
 {data&&tab==='profile'&&<Profile user={data} onSaved={loadUser} setError={scopedError}/>}
 {data&&tab==='errors'&&<ErrorLog initial={data} setError={scopedError}/>}
 {Array.isArray(data)&&tab==='autos'&&<div className="auto-grid">{data.map(row=><article className="card auto-card" key={row.user_login_id}><div><h3>{row.user_name}</h3><small>{row.user_login_id}</small></div><span className={`status-pill ${row.auto_on?'on':'off'}`}>{row.auto_on?'자동매매 사용 중':'자동매매 중지'}</span><p>{row.key_registered?'Upbit API 키가 등록되어 있습니다.':'API 키 등록 후 사용할 수 있습니다.'}</p><button className={row.auto_on?'danger':'primary'} disabled={!row.key_registered||pending.includes(`auto-${row.user_login_id}`)} onClick={()=>mutate(`auto-${row.user_login_id}`,()=>api(`/admin/autos/${encodeURIComponent(row.user_login_id)}`,{method:'PUT',body:JSON.stringify({auto_on:!row.auto_on})}),{refresh:true})}>{pending.includes(`auto-${row.user_login_id}`)?'변경 중…':row.auto_on?'자동매매 끄기':'자동매매 켜기'}</button></article>)}</div>}
 {Array.isArray(data)&&tab==='settings'&&<Settings rows={data} pending={pending} onChange={(index,key,value)=>setData(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row))} onSave={saveSetting}/>}
 {data&&tab==='users'&&<Table rows={data}/>}
 {data&&tab==='mail'&&<><Table rows={data}/><button className="primary add-button" disabled={pending.includes('mail')} onClick={()=>{const email=prompt('추가할 이메일 주소');if(email?.trim())mutate('mail',()=>api('/admin/mail-targets',{method:'POST',body:JSON.stringify({email:email.trim()})}),{refresh:true})}}>메일 수신자 추가</button></>}
 </main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
